apiVersion: v1
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f local.yml -o kube.yaml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: streamlit
      name: streamlit
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: streamlit
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f local.yml -o kube.yaml
            kompose.version: 1.26.1 (a9d05d509)
          creationTimestamp: null
          labels:
            io.kompose.service: streamlit
        spec:
          containers:
            - args:
                - streamlit
                - run
                - app/app.py
              image: curiousish/myrepo:splitmyaudio_emojis
              #imagePullPolicy: Never
              name: streamlit-app2
              ports:
                - containerPort: 8501
                  name: http
              resources: {}
          restartPolicy: Always
    status: {}
kind: List
metadata: {}
